language: python
  python:
    - "3.6"
  install:
    - pip install -r requirements.txt
  script:
    - nosetests --rednose test2 -v -d
  after_success:
    - python-codacy-coverage -r coverage.xml -d ./src/
